def create_maps():
  with open('maze/maze_map1.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   xx  xx xx        x\n')
    outfile.write('x     x     xxxxxxxxxx\n')
    outfile.write('x x    xx  xxxx xxx xx\n')
    outfile.write('  x   x x xx   xxxx  x\n')
    outfile.write('x          xx  xx  x x\n')
    outfile.write('xxxxxxx x      xx  x x\n')
    outfile.write('xxxxxxxxx  x x  xx   x\n')
    outfile.write('x          x x Sx x  x\n')
    outfile.write('xxxxx x  x x x     x x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')
    outfile.close()


  with open('maze/maze_map2.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('    x   x  xx    x   x\n')
    outfile.write('x   x x  xx   xx  xx x\n')
    outfile.write('x x     x    xx x    x\n')
    outfile.write('x x xxx x xx   xxxx  x\n')
    outfile.write('x          xx   x  xxx\n')
    outfile.write('xx  x x x x  xx  x xxx\n')
    outfile.write('xxx x x  x x x  xx   x\n')
    outfile.write('x   x      xxxx xx  xx\n')
    outfile.write('x  xx x xx   x     x x\n')
    outfile.write('x               xxSx x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')
    outfile.close()


  with open('maze/maze_map3.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('xS  x      xxx       x\n')
    outfile.write('x     xxx      x xx xx\n')
    outfile.write('x x x     x x x  xx xx\n')
    outfile.write('x x   x xxxxx  x xx  x\n')
    outfile.write('xx xx xxx x x  x xxxxx\n')
    outfile.write('x    x xx         x xx\n')
    outfile.write('          xxxx xxx   x\n')
    outfile.write('x     xx     x   x xxx\n')
    outfile.write('xx      x  x       x x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')
    outfile.close()


  with open('maze/maze_map4.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   x x  x xxx       x\n')
    outfile.write('xx   xx         xxx xx\n')
    outfile.write('x x x   x x x x xxx xx\n')
    outfile.write('x x  xx x xx  x  xx  x\n')
    outfile.write('xx  xxx Sxxxx xx xxxxx\n')
    outfile.write('xxxxx   xxx xx x     x\n')
    outfile.write('x xx xxx  x  xxxxxx  x\n')
    outfile.write('x         x     xxx  x\n')
    outfile.write('x                   xx\n')
    outfile.write('x xxxxxxxxxxxxxxxxxx  \n')
    outfile.write('x                    x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')
    outfile.close()

  with open('maze/maze_map5.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x   xxx               x    xxxx    x    xx\n')
    outfile.write('   x     xxxx   xx         x      x   x  x\n')
    outfile.write('x  xx       x     xxxxxx         x  x    x\n')
    outfile.write('x  x           xx      x     xx      x x x\n')
    outfile.write('x     x xx     xxx     xxxxxx          x x\n')
    outfile.write('x              xxx   x   x       x     x x\n')
    outfile.write('xx  xxx   xxxxxxx  xxxxx x     xx  x  xx x\n')
    outfile.write('x     x             +          x  xx     x\n')
    outfile.write('x     x             x  x x x x           x\n')
    outfile.write('x  x  x  x  x x   xx x x         xxxxxx  x\n')
    outfile.write('x xx   x         xxx    xx   x   x x     x\n')
    outfile.write('x x    xx   x   x  x      xxx   xx x  x  x\n')
    outfile.write('x x       xxx xx x  xxxx xx  x  x  x     x\n')
    outfile.write('x                 xx            x        x\n')
    outfile.write('x  x xx    x xx   x             x   x  xxx\n')
    outfile.write('xxx    x   x xx x     xxx      xx    x   x\n')
    outfile.write('xx  xx   xx  xxxx x    S  xx    x     x  x\n')
    outfile.write('xx x       x    x     xx        xxx      x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
    outfile.close() 


  with open('maze/maze_map6.txt', 'w') as outfile:
    outfile.write('3\n')
    outfile.write('1 1 -4\n')
    outfile.write('6 4 -5\n')
    outfile.write('5 13 -2\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x+  x    x xxx        \n')
    outfile.write('x     xx       xxxxxxx\n')
    outfile.write('x x x  xx x xxx xxx xx\n')
    outfile.write('x x   x x xx   xxxx  x\n')
    outfile.write('x   xxxxxxxxx+xxxxxx x\n')
    outfile.write('xx  +xx x      xx  x x\n')
    outfile.write('xx xxxxxx  x x  xx   x\n')
    outfile.write('x  x   x   x x  x x  x\n')
    outfile.write('x    x    x x     Sx x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')
    outfile.close()
  
  with open('maze/maze_map7.txt', 'w') as outfile:
    outfile.write('5\n')
    outfile.write('1 1 -50\n')
    outfile.write('6 4 -5\n')
    outfile.write('9 13 -1\n')
    outfile.write('4 17 -3\n')
    outfile.write('9 1 -1\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x+  x    x xxxxxx     \n')
    outfile.write('x     xx       xx  xxx\n')
    outfile.write('x x x  xx x xx     xxx\n')
    outfile.write('x x   x x xxxx x +x  x\n')
    outfile.write('x         xxx  x xxx x\n')
    outfile.write('xx  +xx x      xx  x x\n')
    outfile.write('xx xxxxxx  x x  xx   x\n')
    outfile.write('x  x   x   x x  x xx x\n')
    outfile.write('x+   x    x x+    Sx x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxx')

  with open('maze/maze_map8.txt', 'w') as outfile:
    outfile.write('7\n')
    outfile.write('9 15 -1\n')
    outfile.write('6 8 -4\n')
    outfile.write('10 11 -2\n')
    outfile.write('17 28 -2\n')
    outfile.write('15 20 -5\n')
    outfile.write('15 2 -500\n')
    outfile.write('8 20 -1\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x    xx    x   x      x     x x     xx\n')
    outfile.write('   x     x  x   xx  x      x      x  x\n')
    outfile.write('x                  x x x         x   x\n')
    outfile.write('x  x          x x            xx  x x x\n')
    outfile.write('x     x xx    x  x     x  x x        x\n')
    outfile.write('x       +      x     x             x x\n')
    outfile.write('xx          x x    xxxxx x     x  xx x\n')
    outfile.write('x                  x+         xx     x\n')
    outfile.write('x     x        +    x  x x x x       x\n')
    outfile.write('x  x  xxxxx+x x   xx x x             x\n')
    outfile.write('x xx   x         xxx    xx   x x     x\n')
    outfile.write('x x    xx   x   x  x      xxx   xx x x\n')
    outfile.write('x x       xxx xx x    x   x  x       x\n')
    outfile.write('x                 xx            x    x\n')
    outfile.write('x +x  x    x xx   x +           x  xxx\n')
    outfile.write('xxx    x   x xx x  x  x        xx    x\n')
    outfile.write('xx       xx  xxxx x    S    +     x  x\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
    outfile.close()