with open('maze_map1.txt', 'w') as outfile:
  outfile.write('2\n')
  outfile.write('3 6 -3\n')
  outfile.write('5 14 -1\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x   x   xx xx        x\n')
  outfile.write('x     x     xxxxxxxxxx\n')
  outfile.write('x x   +xx  xxxx xxx xx\n')
  outfile.write('  x   x x xx   xxxx  x\n')
  outfile.write('x          xx +xx  x x\n')
  outfile.write('xxxxxxx x      xx  x x\n')
  outfile.write('xxxxxxxxx  x x  xx   x\n')
  outfile.write('x          x x Sx x  x\n')
  outfile.write('xxxxx x  x x x     x x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')



with open('maze_map2.txt', 'w') as outfile:
  outfile.write('4\n')
  outfile.write('1 10 -2\n')
  outfile.write('3 6 -3\n')
  outfile.write('5 13 -1\n')
  outfile.write('6 5 -5\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('xxx     x +xx        x\n')
  outfile.write('    xxx     xxxxxxxxxx\n')
  outfile.write('x x   +xx    xx xxx xx\n')
  outfile.write('x x xxx x xx   xxxx  x\n')
  outfile.write('x    xx    xx+  x  x x\n')
  outfile.write('xx xx+xxx x  xx  x xxx\n')
  outfile.write('xx xxxxxxx x x  xxx  x\n')
  outfile.write('x      xx  xxxx xx  xx\n')
  outfile.write('x xxx x  x   x     x x\n')
  outfile.write('x xxx x  xx     xxSx x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')



with open('maze_map3.txt', 'w') as outfile:
  outfile.write('2\n')
  outfile.write('1 1 -4\n')
  outfile.write('6 4 -2\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x+  x    x xxx        \n')
  outfile.write('x     xx       xxxxxxx\n')
  outfile.write('x x x  xx x xxx xxx xx\n')
  outfile.write('x x   x x xx   xxxx  x\n')
  outfile.write('x   xxxxxxxxx xxxxxx x\n')
  outfile.write('xx  +xx x      xx  x x\n')
  outfile.write('xx xxxxxx  x x  xx   x\n')
  outfile.write('x  x   x   x x  x x  x\n')
  outfile.write('x    x    x x     Sx x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')


with open('maze_map4.txt', 'w') as outfile:
  outfile.write('2\n')
  outfile.write('8 9 -1\n')
  outfile.write('2 1 -3\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x   x    x xxx       x\n')
  outfile.write('x+    xx       xxxx xx\n')
  outfile.write('x x x  xx x x x xxx xx\n')
  outfile.write('x x   x x xx  xxxxx  x\n')
  outfile.write('xS  xxxxxxxxx xxxxxx x\n')
  outfile.write('xxxxxxx xxx  x     x x\n')
  outfile.write('          xx x xxx   x\n')
  outfile.write('x  xxxxx +xx x xxxxxxx\n')
  outfile.write('xxxxxx         xxx x x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')


with open('maze_map5.txt', 'w') as outfile:
  outfile.write('2\n')
  outfile.write('8 9 -2\n')
  outfile.write('2 2 -3\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x   x    x xxx       x\n')
  outfile.write('xx+   xx        xxx xx\n')
  outfile.write('x x x   x x x x xxx xx\n')
  outfile.write('x x  xx x xx  x  xx  x\n')
  outfile.write('xx  xxx Sxxxx xx xxx x\n')
  outfile.write('xxxxx   xxx  x     x x\n')
  outfile.write('x xx xxx     x xxx   x\n')
  outfile.write('x        +xx   xxxxxxx\n')
  outfile.write('x xxxxxxxxx xxxxxx    \n')
  outfile.write('x                  x x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')
